/**
 * Придумал товары.
 * В будущем - подтягивать из БД
 */
export const cardsInfo = [
  {
    id: 1,
    price: "60.0",
    name: "Гладь с рисунком «горох»",
    article: "1911-2",
    quantity: 1,
  },
  {
    id: 2,
    price: "60.0",
    name: "Гладь с рисунком «ромбы»",
    article: "1911-3",
    quantity: 1,
  },
  {
    id: 3,
    price: "60.0",
    name: "Гладь с рисунком «диагональ»",
    article: "1911-4",
    quantity: 1,
  },
  {
    id: 4,
    price: "60.0",
    name: "Гладь с рисунком «горох»",
    article: "1915",
    quantity: 1,
  },
  {
    id: 5,
    price: "65.0",
    name: "Гладь с рисунком «волны»",
    article: "1920-1",
    quantity: 1,
  },
  {
    id: 6,
    price: "65.0",
    name: "Гладь с рисунком «зигзаг»",
    article: "1920-2",
    quantity: 1,
  },
  {
    id: 7,
    price: "70.0",
    name: "Гладь с рисунком «листья»",
    article: "1925-3",
    quantity: 1,
  },
  {
    id: 8,
    price: "70.0",
    name: "Гладь с рисунком «цветы»",
    article: "1925-4",
    quantity: 1,
  },
  {
    id: 9,
    price: "75.0",
    name: "Гладь с рисунком «клетка»",
    article: "1930-1",
    quantity: 1,
  },
  {
    id: 10,
    price: "75.0",
    name: "Гладь с рисунком «полосы»",
    article: "1930-2",
    quantity: 1,
  },
  {
    id: 11,
    price: "80.0",
    name: "Гладь с рисунком «абстракция»",
    article: "1935-1",
    quantity: 1,
  },
  {
    id: 12,
    price: "80.0",
    name: "Гладь с рисунком «геометрия»",
    article: "1935-2",
    quantity: 1,
  },
  {
    id: 13,
    price: "85.0",
    name: "Гладь с рисунком «мозаика»",
    article: "1940-1",
    quantity: 1,
  },
  {
    id: 14,
    price: "85.0",
    name: "Гладь с рисунком «узоры»",
    article: "1940-2",
    quantity: 1,
  },
  {
    id: 15,
    price: "90.0",
    name: "Гладь с рисунком «кружево»",
    article: "1945",
    quantity: 1,
  },
];
